services:
  database:
    image: postgres:16.3
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - keycloak

  server:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://database:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_LOG: console
      KC_LOG_LEVEL: debug
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./providers:/opt/keycloak/providers
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - database
    command: ["start-dev"]
    networks:
      - keycloak

volumes:
  pgdata:

networks:
  keycloak:
    driver: bridge
